FROM maven:3.6-jdk-8-alpine as build
WORKDIR /app
COPY pom.xml .
RUN mvn -e -B dependency:resolve
COPY src ./src
RUN mvn -e -B package

FROM openjdk:8-jre-alpine
COPY --from=build /app/target/jb-hello-world-maven-0.1.0.jar /tmp
WORKDIR /tmp
CMD ["java", "-jar", "jb-hello-world-maven-0.1.0.jar"]