version: "3"

services:
  web:
    container_name: nginx_task6
    image: nginx:alpine
    ports:
      - "10086:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
    - tomcat
    
  tomcat:
    container_name: tomcat_task6
    image: tomcat:8.0