version: "3"

# There're 2 services: frontend and backend
services:
  frontend:
    container_name: frontend_web
    # image to be used for Front-end
    image: nginx:alpine
    volumes:
    # Mounting nginx' home page into the container
    # Use relative path, from the current directory
    # (with socker-compose.yml)
    - ./frontend/index.html:/etc/nginx/html/index.html
    # Mounting Nginx backend configuration
    - ./frontend/backend.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 80:80

  backend:
    image: tomcat:8.5.55
    container_name: backend_tomcat
    volumes:
    # You can specify absolute path also
    - /tasks/7/backend/tomcat-app.war:/usr/local/tomcat/webapps/tomcat-app.war:ro